### ISSUE TITLE
Mod no longer recognized in game

### ISSUE THREAD

**Issue by m1jordanallen** [lucidagrande/statclock#1]
Updated to statclock-v2.0-mc1.10.2 and unless I am derping hard, the mod is no longer recognized in game.  Originally used the first version on curse and seemed to load fine.  Now it is like the mod doesn't exist.  Also loaded a world and it seemed to remove every item from the world as if I removed the mod.

**Comment by lucidagrande** [comment]
Oops! Used the wrong jar file, re-uploaded 2.0 to curse and should be available in a couple of hours. Sorry for the late response! And thanks for the heads up.
